import type { BoardsmithBuildModel } from "@/lib/build-model/build-model-schema";
import { summarizeCutListReview, type CutListReviewSummary } from "@/lib/plans/cut-list-review";
import { summarizeExportReadiness, type ExportReadinessSummary } from "@/lib/plans/export-readiness";
import { summarizeMaterialReview, type MaterialReviewSummary } from "@/lib/plans/material-summary";
import { summarizeGeneratedPlanReview, type GeneratedPlanReviewSummary } from "@/lib/plans/plan-quality";
import type { GeneratedPlan, GeneratedProjectPlanRecord } from "@/lib/plans/plan-schema";
import { projectTypeLabels, toolLabels, type Project } from "@/lib/projects/types";

export type PrintablePlanBuildModelSource = "saved" | "derived";

export type PrintablePlanManifestInput = {
  project: Project;
  planRecord: GeneratedProjectPlanRecord | null;
  buildModel: BoardsmithBuildModel;
  buildModelSource: PrintablePlanBuildModelSource;
};

export type PrintablePlanManifest = {
  manifestVersion: "1.0";
  project: {
    id: string;
    title: string;
    projectType: Project["project_type"];
    projectTypeLabel: string;
    skillLevel: Project["skill_level"];
    status: Project["status"];
    intake: {
      dimensions: string;
      material: string;
      tools: string[];
      intendedUse: string;
      styleNotes: string | null;
      safetyReviewRequired: boolean;
      safetyFlags: string[];
    };
  };
  generatedPlan: {
    id: string;
    createdAt: string;
    modelName: string;
    summary: string;
    confidenceLevel: GeneratedPlan["confidence_level"];
    estimatedDifficulty: GeneratedPlan["estimated_difficulty"];
    estimatedTime: string;
  } | null;
  buildModel: {
    available: boolean;
    source: PrintablePlanBuildModelSource;
    schemaVersion: BoardsmithBuildModel["schemaVersion"];
    units: BoardsmithBuildModel["units"];
    confidenceLevel: BoardsmithBuildModel["confidence"]["level"];
    pieceCount: number;
    materialCount: number;
    operationCount: number;
  };
  materials: MaterialReviewSummary;
  cutList: CutListReviewSummary | null;
  planReview: GeneratedPlanReviewSummary | null;
  exportReadiness: ExportReadinessSummary | null;
  sections: {
    projectSummary: string | null;
    buildSteps: GeneratedPlan["assembly_steps"];
    modeledOperations: BoardsmithBuildModel["operations"];
    safetyNotes: string[];
    safetyFlags: BoardsmithBuildModel["safety"]["flags"];
    assumptions: string[];
    unresolvedQuestions: string[];
    finishingSteps: string[];
    beginnerTips: string[];
    futureExportReadinessNotes: string[];
    tools: string[];
  };
  disclaimers: string[];
  futureExportNotes: string[];
};

function formatProjectDimensions(project: Project): string {
  return `${project.width_inches.toString()} x ${project.height_inches.toString()} x ${project.depth_inches.toString()} in`;
}

function formatProjectMaterial(project: Project): string {
  return `${project.material_type}, ${project.material_thickness_inches.toString()} in thick`;
}

function generatedPlanSummary(planRecord: GeneratedProjectPlanRecord | null) {
  if (!planRecord) return null;

  return {
    id: planRecord.id,
    createdAt: planRecord.created_at,
    modelName: planRecord.model_name,
    summary: planRecord.plan_json.project_summary,
    confidenceLevel: planRecord.confidence_level,
    estimatedDifficulty: planRecord.plan_json.estimated_difficulty,
    estimatedTime: planRecord.plan_json.estimated_time,
  };
}

function planSections(plan: GeneratedPlan | null, buildModel: BoardsmithBuildModel): PrintablePlanManifest["sections"] {
  return {
    projectSummary: plan?.project_summary ?? null,
    buildSteps: plan?.assembly_steps ?? [],
    modeledOperations: buildModel.operations,
    safetyNotes: plan?.safety_notes ?? [],
    safetyFlags: buildModel.safety.flags,
    assumptions: [...new Set([...(plan?.assumptions ?? []), ...buildModel.assumptions])],
    unresolvedQuestions: buildModel.unresolvedQuestions,
    finishingSteps: plan?.finishing_steps ?? [],
    beginnerTips: plan?.beginner_tips ?? [],
    futureExportReadinessNotes: [...new Set([...(plan?.svg_readiness_notes ?? []), ...buildModel.exportReadiness.notes])],
    tools: plan?.tools ?? [],
  };
}

function baseDisclaimers(buildModel: BoardsmithBuildModel): string[] {
  return [
    "Boardsmith plans are planning aids, not professional engineering reviews.",
    "Verify dimensions, materials, hardware, tool setup, and site conditions before cutting or building.",
    "No export, CAD, CNC, PDF, SVG, or DXF output is generated by this manifest.",
    ...buildModel.safety.disclaimers,
  ];
}

function futureExportNotes(planRecord: GeneratedProjectPlanRecord | null, exportReadiness: ExportReadinessSummary | null): string[] {
  if (!planRecord || !exportReadiness) {
    return ["Generate and validate a plan before using this manifest for future print or export work."];
  }

  const notes = [
    "This manifest is an internal data foundation only; it does not create files or downloads.",
    ...exportReadiness.exportReadinessNotes,
    ...exportReadiness.topMessages,
  ];

  if (exportReadiness.exportCandidates.length > 0) {
    notes.push(`Future export candidates: ${exportReadiness.exportCandidates.join(", ")}.`);
  }

  return [...new Set(notes)];
}

export function createPrintablePlanManifest({
  project,
  planRecord,
  buildModel,
  buildModelSource,
}: PrintablePlanManifestInput): PrintablePlanManifest {
  const plan = planRecord?.plan_json ?? null;
  const planReview = plan ? summarizeGeneratedPlanReview(plan, buildModel, { buildModelSource }) : null;
  const exportReadiness = plan ? summarizeExportReadiness(plan, buildModel, { buildModelSource }) : null;

  return {
    manifestVersion: "1.0",
    project: {
      id: project.id,
      title: project.title,
      projectType: project.project_type,
      projectTypeLabel: projectTypeLabels[project.project_type],
      skillLevel: project.skill_level,
      status: project.status,
      intake: {
        dimensions: formatProjectDimensions(project),
        material: formatProjectMaterial(project),
        tools: project.tools_available.map((tool) => toolLabels[tool]),
        intendedUse: project.intended_use,
        styleNotes: project.style_notes || null,
        safetyReviewRequired: project.safety_review_required,
        safetyFlags: project.safety_flags,
      },
    },
    generatedPlan: generatedPlanSummary(planRecord),
    buildModel: {
      available: true,
      source: buildModelSource,
      schemaVersion: buildModel.schemaVersion,
      units: buildModel.units,
      confidenceLevel: buildModel.confidence.level,
      pieceCount: buildModel.pieces.length,
      materialCount: buildModel.materials.length,
      operationCount: buildModel.operations.length,
    },
    materials: summarizeMaterialReview(plan, buildModel),
    cutList: plan ? summarizeCutListReview(plan, buildModel) : null,
    planReview,
    exportReadiness,
    sections: planSections(plan, buildModel),
    disclaimers: [...new Set(baseDisclaimers(buildModel))],
    futureExportNotes: futureExportNotes(planRecord, exportReadiness),
  };
}
